# Generated by Django 3.1.5 on 2021-01-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_votings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
