# Generated by Django 3.1.5 on 2021-02-06 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_votings', '0004_allvotings_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('stat', models.IntegerField()),
                ('ans', models.CharField(default=None, max_length=500)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_votings.allvotings')),
            ],
        ),
    ]
